### ISSUE TITLE
[ERROR]:Cant get transform for distance traveled counter "darpa" passed to lookupTransform argument source_frame does not exist.

### ISSUE THREAD

**Issue by wanghao1666** [subtchallenge/tunnel_urban_reference_datasets#2]
When I enter the following command:` roslaunch tunnel_ckt_launch remap.launch bag:=sr_B_route1.bag orbslam:=true course:=sr config:=B`, trying to run the dataset with orbslam2, i get the following error:`[ERROR] [1652531568.440679340, 1566248611.691736079]: Cant get transform for distance traveled counter "darpa" passed to lookupTransform argument source_frame does not exist.`How can i fix it ?

**Comment by fengye4242** [comment]
@wanghao1666 I have the same issue, could you please tell me how to fix it. Thanks
